---
- name: Change password
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: always
  with_items: "{{ accounts }}"
  no_log: true
