- name: Setting GPU memory split to {{ gpu_mem }}mb
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^#?gpu_mem'
    line: 'gpu_mem={{ gpu_mem }}'
    insertafter: EOF
    state: present
