- name: Check if log2ram is already installed
  stat:
    path: /etc/systemd/system/log2ram.service
  register: log2ram_installed

- name: Stop log2ram service
  service:
    name: log2ram
    state: stopped
  when: log2ram_installed.stat.exists

- name: Download log2ram services from master branch
  get_url:
    url: "https://github.com/azlux/log2ram/archive/master.tar.gz"
    dest: "/tmp/log2ram.tar.gz"
    mode: 0755

- name: Extract archive
  unarchive:
    src: /tmp/log2ram.tar.gz
    dest: /tmp/
    remote_src: true

- name: Set execute permissions
  file:
    path: /tmp/log2ram-master/install.sh
    mode: u+x

- name: Install log2ram
  command:
    cmd: sh install.sh
    chdir: /tmp/log2ram-master/
  changed_when: false

- name: Change RAM size of log folder to {{ log2ram_size }}mb
  lineinfile:
    path: /etc/log2ram.conf
    regexp: '^SIZE='
    line: 'SIZE={{ log2ram_size }}M'

- name: Ensure log2ram is running on startup
  systemd:
    name: log2ram
    daemon_reload: true
    state: started
    enabled: true
