---
- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600
  notify: reboot

- include: additional-packages.yml
  when: packages is defined

- include: change-hostname.yml
  when: hostname_prefix is defined

- include: manage-users.yml
  when: accounts is defined
  no_log: true


- include: ssh.yml

# - include: log2ram.yml
#   when: log2ram_size is defined

- include: disable-ipv6.yml
  when: disable_ipv6_interfaces is defined

- include: disable-hdmi.yml
  when: disable_hdmi

- include: nfs-mount.yml
  when: nfs_mount is defined

- include: gpu-mem-split.yml
  when: gpu_mem is defined
  notify: reboot
